const words = {
  Easy: [
    'apple',
    'banana',
    'cat',
    'dog',
    'elephant',
    'fish',
    'house',
    'tree',
    'water',
    'world',
  ],
  Moderate: [
    'beautiful',
    'comfortable',
    'difficult',
    'enormous',
    'fantastic',
    'government',
    'important',
    'intelligent',
    'interesting',
    'language',
  ],
  Hard: [
    'bureaucracy',
    'conscientious',
    'extracurricular',
    'heterogeneous',
    'infinitesimal',
    'juxtaposition',
    'labyrinth',
    'meticulous',
    'photosynthesis',
    'surreptitious',
  ],
}

export default words
